name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk wget unzip
          
      - name: Set up Android SDK
        run: |
          # Download command line tools and unzip them into the SDK folder
          mkdir -p $HOME/Android
          cd $HOME/Android
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          
          # Set ANDROID_SDK_ROOT and update PATH
          echo "export ANDROID_SDK_ROOT=$HOME/Android" >> ~/.bashrc
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/36.0.0:$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Accept Android SDK licenses
        run: |
          # Accept SDK licenses
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install necessary SDK components
        run: |
          # Install required SDK packages
          $HOME/Android/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-28" "sources;android-28"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install cython
          pip install buildozer
          pip install kivy

      - name: Build APK with Buildozer
        run: |
          # Set the correct paths and permissions for Buildozer
          cd /storage/emulated/0/flappybird
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flappybird-apk
          path: /storage/emulated/0/flappybird/bin/*.apk
