name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java environment
        run: sudo apt-get install openjdk-8-jdk -y

      - name: Set up Android SDK
        run: |
          # Install SDK tools
          sudo apt-get install wget unzip -y
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
          unzip android-sdk.zip -d $HOME/Android
          rm android-sdk.zip
          
          # Add SDK to PATH
          echo "export ANDROID_SDK_ROOT=$HOME/Android" >> ~/.bashrc
          echo "export PATH=$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install necessary SDK components
        run: |
          sdkmanager "platform-tools"
          sdkmanager "build-tools;36.0.0-rc3"
          sdkmanager "platforms;android-28"
          sdkmanager "sources;android-28"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install cython
          pip install buildozer
          pip install kivy

      - name: Build APK with Buildozer
        run: |
          # Set the correct paths and permissions for Buildozer
          cd /storage/emulated/0/flappybird
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flappybird-apk
          path: /storage/emulated/0/flappybird/bin/*.apk
