name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies and setup Android SDK
      - name: Install Android SDK tools
        run: |
          # Define SDK location
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          # Download and install SDK command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O $HOME/commandlinetools.zip
          unzip -q $HOME/commandlinetools.zip -d $ANDROID_SDK_ROOT
          rm $HOME/commandlinetools.zip

          # Rename cmdline-tools folder to latest
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools" ]; then
            mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-old
          fi
          mv $ANDROID_SDK_ROOT/cmdline-tools-old $ANDROID_SDK_ROOT/cmdline-tools/latest

          # Update SDK manager
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update

      # Accept SDK licenses
      - name: Accept SDK licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      # Install required SDK packages
      - name: Install required SDK packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-30"

      # Build APK using Buildozer
      - name: Build APK with Buildozer
        run: |
          # Install Buildozer if not already installed
          pip install buildozer

          # Navigate to project directory
          cd /path/to/your/project

          # Run Buildozer to build APK
          buildozer android debug
