name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Use the latest stable Ubuntu version for compatibility

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Cache Buildozer global directory (to speed up subsequent builds)
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      # Step 3: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 4: Install system dependencies (including AIDL and required tools)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            openjdk-17-jdk \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            autoconf \
            automake \
            build-essential \
            python3-dev \
            libtool \
            cmake \
            unzip \
            wget \
            pkg-config \
            libncurses5 libstdc++6 lib32z1 libbz2-1.0 lib32stdc++6

      # Step 5: Install Android SDK and command-line tools
      - name: Install Android SDK
        run: |
          mkdir -p ~/android-sdk/cmdline-tools
          cd ~/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=~/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest"

      # Step 6: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --force-reinstall cython
          pip install buildozer

      # Step 7: Prepare AIDL
      - name: Ensure AIDL
        run: |
          export ANDROID_HOME=~/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          sdkmanager "platforms;android-34" --install

      # Step 8: Run Buildozer to build the app
      - name: Build with Buildozer
        run: |
          export ANDROID_HOME=~/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      # Step 9: Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flappybird-apk
          path: bin/*.apk
