name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Use Ubuntu 24.04 for compatibility

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Cache Buildozer global directory (to speed up subsequent builds)
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      # Step 3: Set up Python 3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 4: Install system dependencies for Buildozer and Android
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            openjdk-17-jdk \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            autoconf \
            automake \
            build-essential \
            python3-dev \
            libtool \
            cmake \
            unzip \
            wget \
            pkg-config \
            libstdc++6 \
            lib32z1 \
            libbz2-1.0 \
            lib32stdc++6 \
            curl

      # Step 5: Install Android SDK tools
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      # Step 6: Accept licenses and install Android SDK components
      - name: Install Android SDK components
        run: |
          source $GITHUB_ENV
          sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest"

      # Step 7: Install Python dependencies for Buildozer
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --force-reinstall cython
          pip install buildozer

      # Step 8: Build with Buildozer
      - name: Build with Buildozer
        run: |
          source $GITHUB_ENV
          buildozer android debug

      # Step 9: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flappybird-apk
          path: bin/*.apk
