name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Cache dependencies (optional but recommended)
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      # Set up Python and install dependencies
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      # Run the build command
      - name: Build with Buildozer
        run: buildozer android debug

      # Upload build artifacts (APK file)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flappybird-apk
          path: /path/to/your/apk/file
