name: Build and Package APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment and install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install necessary Python dependencies directly
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install buildozer

    # Step 3: Install Android SDK and Build Tools
    - name: Install Android SDK and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

        # Set environment variables for SDK
        echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/android-sdk/tools:/usr/local/android-sdk/platform-tools:/usr/local/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

        # Create the necessary directories if they do not exist and grant write permissions
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo chmod -R 777 /usr/local/android-sdk  # Grant write permissions to the SDK directory

        # Download and unzip Android SDK Command-line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -P /tmp
        unzip /tmp/commandlinetools-linux-8512546_latest.zip -d /usr/local/android-sdk/cmdline-tools
        rm /tmp/commandlinetools-linux-8512546_latest.zip

        # Create a symlink to 'latest' so that sdkmanager can be found
        sudo ln -s /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest

        # Ensure sdkmanager exists in the specified location
        ls -la /usr/local/android-sdk/cmdline-tools/latest/bin/

        # Accept all SDK licenses
        yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install necessary SDK components (including NDK and platform tools)
        /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
        /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147" "extras;android;m2repository"

    # Step 4: Build APK using Buildozer
    - name: Build APK
      run: |
        # Build the APK using Buildozer
        cd /storage/emulated/0/flappybird
        buildozer android debug
        buildozer android deploy run
