name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: /home/runner/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      # Install Android SDK Command-Line Tools
      - name: Install Android SDK Command-Line Tools
        run: |
          # Define SDK location
          SDK_DIR=/home/runner/android-sdk
          
          # Download the command-line tools zip file
          echo "Downloading Android SDK command-line tools..."
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o commandlinetools.zip
          
          # Create the android-sdk folder if not present
          mkdir -p $SDK_DIR

          # Unzip the SDK tools into the android-sdk directory
          echo "Unzipping command-line tools..."
          unzip -o commandlinetools.zip -d $SDK_DIR/cmdline-tools

          # Check if the unzip worked and the directory structure is correct
          ls -alh $SDK_DIR/cmdline-tools

          # Rename the cmdline-tools folder to 'latest'
          echo "Renaming cmdline-tools folder..."
          mv $SDK_DIR/cmdline-tools $SDK_DIR/cmdline-tools-latest

          # Accept licenses
          echo "Accepting SDK licenses..."
          yes | $SDK_DIR/cmdline-tools-latest/bin/sdkmanager --licenses

          # Install platform tools and build tools
          echo "Installing SDK components..."
          $SDK_DIR/cmdline-tools-latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      # Build the APK (customize this step as per your project requirements)
      - name: Build APK
        run: |
          # Add your build commands here (e.g., using gradle, ant, etc.)
          echo "Building APK..."
