


name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip zip unzip
        pip install buildozer cython

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer -v -c ./buildozer.spec android debug
