name: Build APK for flappybird

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        ls -al  # List files to check if buildozer.spec is in the correct location

    # Download Android SDK Command Line Tools
    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p /home/runner/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip -o commandlinetools.zip -d /home/runner/android-sdk/cmdline-tools
        rm commandlinetools.zip
        mkdir -p /home/runner/android-sdk/cmdline-tools/latest
        mv /home/runner/android-sdk/cmdline-tools/cmdline-tools/* /home/runner/android-sdk/cmdline-tools/latest
        mkdir -p /home/runner/android-sdk/tools/bin
        ln -sf /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager /home/runner/android-sdk/tools/bin/sdkmanager

    - name: Accept Android SDK Licenses
      run: yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install SDK Components
      run: |
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV

    - name: Install Buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        pip install buildozer
        buildozer -v android debug

    - name: Upload APK to GitHub Releases
      if: success()
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'bin/*.apk'
        token: ${{ secrets.GITHUB_TOKEN }}
