name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v2

      # Cache Buildozer global directory (optional but recommended)
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      # Install required dependencies (e.g., Java, Android SDK, NDK)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y zip unzip
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          sudo apt-get install -y libncurses5
          sudo apt-get install -y libstdc++6

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Buildozer
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      # Install Android dependencies using Buildozer
      - name: Install Android SDK/NDK dependencies
        run: |
          buildozer android clean  # This will install dependencies like SDK and NDK

      # Run Buildozer to build the APK
      - name: Build APK with Buildozer
        run: buildozer android debug

      # Upload the APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flappybird-apk
          path: bin/flappybird-1.0-debug.apk
