name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Buildozer version
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          buildozer --version

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y zip unzip
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          sudo apt-get install -y libncurses5
          sudo apt-get install -y libstdc++6

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Install Android SDK/NDK dependencies
        run: |
          buildozer android clean

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flappybird-apk
          path: bin/flappybird-1.0-debug.apk
