name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Android SDK
      run: |
        # Install required dependencies for Android SDK
        sudo apt update
        sudo apt install -y openjdk-8-jdk wget unzip
        mkdir -p $HOME/Android/Sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/Android/Sdk
        rm commandlinetools-linux-8512546_latest.zip

        # Set environment variables for Android SDK
        echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_SDK_ROOT/tools" >> $GITHUB_ENV

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt install -y python3 python3-pip zip unzip
        pip install buildozer cython

    - name: Install Android SDK packages
      run: |
        yes | sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer -v -c ./buildozer.spec android debug


