name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Buildozer and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -o sdk-tools.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm sdk-tools.zip

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android Build Tools
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Verify AIDL Tool
        run: |
          if [ ! -f "$ANDROID_HOME/build-tools/31.0.0/aidl" ]; then
            echo "AIDL not found. Please check Build-Tools installation."
            exit 1
          fi

      - name: Build the APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug
