name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04  # Use Ubuntu 24.04 for compatibility

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('**/buildozer.spec') }}

      # Step 3: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 4: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            openjdk-17-jdk \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            autoconf \
            automake \
            build-essential \
            python3-dev \
            libtool \
            cmake \
            unzip

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      # Step 6: Run Buildozer to build the app
      - name: Build with Buildozer
        run: buildozer android debug

      # Step 7: Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flappybird-apk
          path: bin/*.apk
